from typing import Protocol

from core.entities import Budget, Category, Expense, Income, User
from core.enums import CategoryType


class PasswordService(Protocol):
    def hash_password(self, password: str) -> str: ...


class UserService(Protocol):
    def create(self, first_name: str, last_name: str, login: str, password_hash: str) -> User: ...

    def find_by_login(self, login: str) -> User | None: ...

    def get(self, user_id: str) -> User | None: ...

    def update_first_name(self, first_name: str) -> User: ...

    def update_last_name(self, last_name: str) -> User: ...

    def change_password(self, password: str) -> User: ...

    def delete(self, user_id: str) -> None: ...


class BudgetService(Protocol):
    def create(self, name: str, amount: float, user_id: str, description: str | None) -> Budget: ...

    def get(self, budget_id: str) -> Budget | None: ...

    def find(self, user_id: str) -> Budget | None: ...

    def change_budget(
        self,
        name: str | None = None,
        description: str | None = None,
        amount: float | None = None,
    ) -> Budget: ...

    def delete(self, budget_id: str) -> None: ...


class CategoryService(Protocol):
    def create(self, user_id: str, name: str, description: str | None) -> Category: ...

    def get(self, category_id: str) -> Category | None: ...

    def find(self, user_id: str, type_: CategoryType | None = None) -> list[Category]: ...

    def change_category(
        self,
        name: str | None = None,
        description: str | None = None,
        type_: CategoryType | None = None,
        is_archived: bool | None = None,
    ) -> Category: ...

    def delete(self, category_id: str) -> None: ...


class ExpenseService(Protocol):
    def create(self, amount: float, category_id: str, user_id: str, description: str | None = None) -> Expense: ...

    def get(self, expense_id: str) -> Expense | None: ...

    def find(self, user_id: str) -> Expense | None: ...

    def change_expense(
        self,
        amount: float | None = None,
        category_id: str | None = None,
        description: str | None = None,
    ) -> Expense: ...

    def delete(self, expense_id: str) -> None: ...


class IncomeService(Protocol):
    def create(self, amount: float, category_id: str, user_id: str, description: str | None = None) -> Income: ...

    def get(self, income_id: str) -> Income | None: ...

    def find(self, user_id: str) -> Income | None: ...

    def change_income(
        self,
        amount: float | None = None,
        category_id: str | None = None,
        description: str | None = None,
    ) -> Income: ...

    def delete(self, income_id: str) -> None: ...
